######################################################################
# Automatically generated by qmake (2.01a) Mon Sep 3 01:48:35 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += logf.cpp
